# Generated by Django 5.0.2 on 2024-11-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_first_login_ip_customuser_last_login_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registered_devices_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tracked_devices_count',
            field=models.IntegerField(default=0),
        ),
    ]
