# Generated by Django 5.0.2 on 2024-11-15 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='device_images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='device_images')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('imei1', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('imei2', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_tracked', models.BooleanField(default=False)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('building_number', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('nearby_landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('location_accuracy', models.CharField(blank=True, max_length=50, null=True)),
                ('altitude', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('speed', models.CharField(blank=True, max_length=50, null=True)),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('connected_wifi', models.CharField(blank=True, max_length=100, null=True)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
