# Generated by Django 5.0.2 on 2024-11-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_device_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
