# Generated by Django 4.2.23 on 2025-07-14 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0002_trackablelink_campaign_params_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='trackablelink',
            name='language',
        ),
        migrations.RemoveField(
            model_name='trackablelink',
            name='referrer',
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('lost', 'Lost'), ('recovered', 'Recovered')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei1',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=15, null=True, unique=True)),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei2',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=15, null=True, unique=True)),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_links', to=settings.AUTH_USER_MODEL, to_field='unique_user_id'),
        ),
        migrations.AlterField(
            model_name='trackablelink',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackable_links', to='devices.device'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['unique_device_id'], name='devices_dev_unique__3d6d56_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['imei1'], name='devices_dev_imei1_493ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['imei2'], name='devices_dev_imei2_0372e4_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'status'], name='devices_dev_user_id_2c8247_idx'),
        ),
        migrations.AddIndex(
            model_name='trackablelink',
            index=models.Index(fields=['device', 'is_clicked'], name='devices_tra_device__fff579_idx'),
        ),
    ]
